## DEV IMAGE, DO NOT USE IN PRODUCTION
FROM ubuntu:latest
RUN apt update && apt upgrade -y
WORKDIR /src/
RUN apt install npm golang -y
ADD . .
RUN npm install
RUN go build  -o /bin/intra cmd/intra/main.go
ENTRYPOINT bash

